pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
    stages {
        stage('Checkout') {
            steps {
                sendNotification('started', 'team@example.com')
                git branch: 'solutions',
                    url: 'https://github.com/zhuchengsg/DO400-apps'
            }
        }
        stage('Test') {
            steps {
                dir('simple-calculator') {
                    sh './mvnw clean test'
                }
            }
        }
        stage('Check Style') {
            steps {
                dir('simple-calculator') {
                    script {
                        try {
                            sh './mvnw clean checkstyle:check'
                        } catch (Exception e) {
                            sendWarningAlert("${STAGE_NAME}", 'devs@example.com')
                            unstable("${STAGE_NAME} stage failed!")
                        }
                    }
                }
            }
        }
    }
    post {
        failure {
            sendFailureAlert('team@example.com')
        }
        always {
            sendNotification('finished', 'team@example.com')
        }
    }
}

void sendFailureAlert(String email) {
    mail to: "${email}",
        subject: "Pipeline failed: ${currentBuild.fullDisplayName}",
        body: "The following pipeline failed: ${env.BUILD_URL}"
}
void sendWarningAlert(String stage, String email) {
    mail to: "${email}",
        subject: "${stage} stage failed: ${currentBuild.fullDisplayName}",
        body: "The ${stage} stage failed: ${env.BUILD_URL}"
}
void sendNotification(String action, String email) {
    mail to: "${email}",
        subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}

